apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rollouts-demo
  strategy:
    blueGreen:
      activeService: active
      previewService: preview
      autoPromotionEnabled: true
      prePromotionAnalysis:
        args:
        - name: query
          # Note encoded so it can be used as a query parameter, unencode:
          # irate(haproxy_backend_http_responses_total{exported_namespace='rollouts-demo-prod',route=~'preview',code='5xx'}[1m])>10 or on() vector(0)
          value: irate(haproxy_backend_http_responses_total%7Bexported_namespace='user%USER%-prod',route=~'preview',code='5xx'%7D%5B1m%5D)%3E10%20or%20on()%20vector(0)
        - name: route-url
          value: preview-user%USER%-prod.%SUB_DOMAIN%
        templates:
        - templateName: smoke-tests
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - image: quay.io/openshiftdemos/rollouts-demo:blue
        imagePullPolicy: IfNotPresent
        name: rollouts-demo
        ports:
        - containerPort: 8080
