apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rollouts-demo
  strategy:
    blueGreen:
      activeService: active
      previewService: preview
      autoPromotionEnabled: false
      prePromotionAnalysis:
        args:
        - name: query
          value: irate%28haproxy_backend_http_responses_total%7Bexported_namespace%3D%27rollouts-demo-prod%27%2C%20route%3D~%22bluegreen-preview%22%2C%20code%3D%225xx%22%7D%5B1m%5D%29%20%3E%205%20or%20on%28%29%20vector%280%29
        - name: route-url
          value: ${PREVIEW_ROUTE}
        templates:
        - templateName: smoke-tests
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - image: quay.io/openshiftdemos/rollouts-demo:blue
        imagePullPolicy: IfNotPresent
        name: rollouts-demo
        ports:
        - containerPort: 8080
