apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: rollouts-demo
  namespace: user{{ .Values.user }}-dev
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: rollouts-demo
