apiVersion: v1
kind: Service
metadata:
  labels:
    app: rollouts-demo
  name: rollouts-demo
  namespace: user{{ .Values.user }}-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: rollouts-demo
